"""
Omfattande databas över prejudikat och vägledande domar från Arbetsdomstolen (AD).
Täcker arbetsbrist, turordning, sakliga skäl, avskedande, omplacering, diskriminering,
lojalitetsplikt, alkohol/droger, bisysslor, arbetsskyldighet m.m.
"""

from typing import List, Dict, Any

AD_PRECEDENTS_DATA: List[Dict[str, Any]] = [
    {
        "id": "AD_2023_nr_45",
        "case_number": "AD 2023 nr 45",
        "year": 2023,
        "title": "Sakliga skäl för uppsägning vid bristande arbetsprestation under nya LAS",
        "summary": "Arbetsdomstolen prövade begreppet sakliga skäl (efter 2022 års LAS-reform). En arbetsgivare som genomfört en skälig omplaceringsutredning och gett skriftliga varningar ansågs ha sakliga skäl för uppsägning.",
        "legal_provisions_referenced": ["LAS 7 §", "LAS 7 a §"],
        "parties": "Unionen mot Almega",
        "domskal": "Med 2022 års reform ska inte längre göras någon intresseavvägning eller prognos kring arbetstagarens personliga intresse av att behålla anställningen, utan fokus ligger strikt på om avtalsbrottet är tillräckligt allvarligt och om omplaceringsskyldigheten har fullgjorts.",
        "slut": "Uppsägningen förklaras giltig."
    },
    {
        "id": "AD_2022_nr_12",
        "case_number": "AD 2022 nr 12",
        "year": 2022,
        "title": "Gränsdragning mellan avskedande (18 §) och uppsägning (7 §) vid illojalitet",
        "summary": "En anställd hade förberett konkurrerande verksamhet och kontaktat kunder under anställningstiden. AD fann att agerandet inte var tillräckligt grovt för omedelbart avskedande men utgjorde saklig grund för uppsägning.",
        "legal_provisions_referenced": ["LAS 7 §", "LAS 18 §"],
        "parties": "IF Metall mot Teknikföretagen",
        "domskal": "Avskedande kräver ett sådant grovt åsidosättande av anställningsavtalet att anställningen ska upphöra omedelbart utan uppsägningstid. Att förbereda konkurrens utan faktiskt drift kan motivera uppsägning men inte alltid avskedande.",
        "slut": "Avskedandet ogiltigförklaras, men anställningen upphör genom uppsägning med lön under uppsägningstid."
    },
    {
        "id": "AD_2022_nr_15",
        "case_number": "AD 2022 nr 15",
        "year": 2022,
        "title": "Skadeståndsnivåer vid ogiltigt avskedande och bristande utredning",
        "summary": "En arbetsgivare avskedade en anställd på lösa misstankar utan tillräcklig bevisning. AD ogiltigförklarade avskedandet och dömde ut förhöjt allmänt skadestånd.",
        "legal_provisions_referenced": ["LAS 18 §", "LAS 38 §"],
        "parties": "Handels mot Detaljhandelsbolag",
        "domskal": "När arbetsgivaren avskedar utan minsta fog och bryter mot grundläggande utredningskrav fastställs allmänt skadestånd på en kännbar nivå för att markera lagens skydd.",
        "slut": "Avskedandet ogiltigförklaras och allmänt skadestånd om 150 000 kr utdöms jämte full lön."
    },
    {
        "id": "AD_2021_nr_55",
        "case_number": "AD 2021 nr 55",
        "year": 2021,
        "title": "Olovlig frånvaro och bristande sjukanmälan",
        "summary": "En arbetstagare uteblev från arbetet under två veckor utan giltigt läkarintyg trots upprepade skriftliga uppmaningar. AD ansåg att laglig grund för avskedande förelåg.",
        "legal_provisions_referenced": ["LAS 18 §", "LAS 7 §"],
        "parties": "Handels mot Svensk Handel",
        "domskal": "Upprepad eller långvarig olovlig frånvaro rubbar i grunden arbetsgivarens förtroende och utgör ett grovt avtalsbrott som befriar arbetsgivaren från skyldighet att omplacera.",
        "slut": "Käromålet avslås. Avskedandet var lagligt."
    },
    {
        "id": "AD_2021_nr_41",
        "case_number": "AD 2021 nr 41",
        "year": 2021,
        "title": "Arbetsvägran och arbetsledningsrätt (29/29-principen)",
        "summary": "En anställd vägrade utföra beordrade arbetsuppgifter som låg inom kollektivavtalets tillämpningsområde och den anställdes allmänna yrkeskvalifikationer.",
        "legal_provisions_referenced": ["LAS 7 §", "LAS 18 §", "MBL 4 §"],
        "parties": "Byggnads mot Sveriges Byggindustrier",
        "domskal": "En arbetstagare är skyldig att utföra allt arbete som ryms inom kollektivavtalet och som faller under arbetsgivarens arbetsledningsrätt. Ihållande arbetsvägran utgör sakliga skäl för uppsägning.",
        "slut": "Uppsägningen förklaras sakligt grundad."
    },
    {
        "id": "AD_2020_nr_30",
        "case_number": "AD 2020 nr 30",
        "year": 2020,
        "title": "Turordning vid arbetsbrist – krav på tillräckliga kvalifikationer (LAS 22 §)",
        "summary": "Vid neddragning gjorde en arbetstagare med längre anställningstid gällande rätt till omplacering till en specialistroll. AD prövade innebörden av 'tillräckliga kvalifikationer'.",
        "legal_provisions_referenced": ["LAS 22 §", "LAS 7 §"],
        "parties": "Sveriges Ingenjörer mot Företag X",
        "domskal": "Tillräckliga kvalifikationer innebär inte att arbetstagaren måste behärska tjänsten fullt ut från dag ett, men ska klara de grundläggande kraven efter en rimlig inlärnings- och inskolningsperiod (normalt upp till 6 månader).",
        "slut": "Arbetsgivaren bröt mot turordningsreglerna då arbetstagaren bedömdes ha tillräckliga kvalifikationer. Skadestånd utdömdes."
    },
    {
        "id": "AD_2020_nr_33",
        "case_number": "AD 2020 nr 33",
        "year": 2020,
        "title": "Sakliga skäl vid allvarliga samarbetssvårigheter och hotfull stämning",
        "summary": "Uppsägning av en medarbetare som uppvisat aggressivt beteende mot kollegor och chefer. Arbetsgivaren hade genomfört medling och erbjudit handledning.",
        "legal_provisions_referenced": ["LAS 7 §", "Arbetsmiljölagen 3 kap."],
        "parties": "Vision mot Region Kronoberg",
        "domskal": "När samarbetsproblem är så djupgående att de lamslår arbetsplatsen och arbetsmiljön äventyras, och hjälpinsatser uttömts, finns sakliga skäl för uppsägning.",
        "slut": "Uppsägningen ansågs giltig."
    },
    {
        "id": "AD_2019_nr_44",
        "case_number": "AD 2019 nr 44",
        "year": 2019,
        "title": "Samarbetssvårigheter och kränkande bemötande på arbetsplatsen",
        "summary": "Uppsägning på grund av allvarliga samarbetssvårigheter, kränkande bemötande mot kollegor och chefer samt ovilja att medverka till lösningar.",
        "legal_provisions_referenced": ["LAS 7 §", "Arbetsmiljölagen 3 kap 2 §"],
        "parties": "Kommunal mot Kommun Y",
        "domskal": "När samarbetssvårigheterna är allvarliga, varaktiga och påverkar arbetsmiljön menligt, och omplacering prövats utan framgång, föreligger sakliga skäl för uppsägning.",
        "slut": "Käromålet avslås. Uppsägningen var sakligt grundad."
    },
    {
        "id": "AD_2019_nr_23",
        "case_number": "AD 2019 nr 23",
        "year": 2019,
        "title": "Förmögenhetsbrott mot arbetsgivaren – stöld och manipulation av kassasystem",
        "summary": "En butiksanställd stal varor och manipulerade kvitton till ett värde av några tusen kronor. Arbetsgivaren avskedade personen med omedelbar verkan.",
        "legal_provisions_referenced": ["LAS 18 §"],
        "parties": "Handels mot Butikskedja",
        "domskal": "Arbetsdomstolen ser mycket strängt på förmögenhetsbrott i anställningen. Även stölder av begränsat ekonomiskt värde rubbar förtroendet och motiverar normalt avskedande.",
        "slut": "Avskedandet var lagligt. Käromålet ogillades."
    },
    {
        "id": "AD_2019_nr_54",
        "case_number": "AD 2019 nr 54",
        "year": 2019,
        "title": "Stapling av visstidsanställningar och företrädesrätt vid intermittent anställning",
        "summary": "Prövning av om upprepade korta visstidsanställningar (timanställningar) övergått till en tillsvidareanställning enligt LAS omvandlingsregler.",
        "legal_provisions_referenced": ["LAS 5 §", "LAS 5 a §"],
        "parties": "Hotell- och Restaurangfacket mot Hotellkoncern",
        "domskal": "Arbetstagaren uppnådde mer än tolv månaders sammanlagd anställningstid inom ramen för den lagstadgade ramtiden och anställningen övergick därmed automatiskt till en tillsvidareanställning.",
        "slut": "Fastställelse av tillsvidareanställning samt allmänt skadestånd för brott mot omvandlingsregeln."
    },
    {
        "id": "AD_2018_nr_15",
        "case_number": "AD 2018 nr 15",
        "year": 2018,
        "title": "Drogpåverkan och alkoholmissbruk i säkerhetskänslig miljö / Rehabiliteringsansvar",
        "summary": "En anställd i säkerhetsklassat arbete testades positivt för narkotika och vägrade delta i arbetsgivarens erbjudna rehabiliteringsprogram.",
        "legal_provisions_referenced": ["LAS 7 §", "LAS 18 §", "SFB 30 kap."],
        "parties": "Seko mot Tågoperatör",
        "domskal": "Arbetsgivaren har ett långtgående rehabiliteringsansvar vid missbrukssjukdom, men om arbetstagaren utan giltig anledning avböjer erbjuden rehabilitering föreligger grund för uppsägning.",
        "slut": "Uppsägningen var giltig."
    },
    {
        "id": "AD_2018_nr_62",
        "case_number": "AD 2018 nr 62",
        "year": 2018,
        "title": "Upprepad sen ankomst och misskötsamhet efter LAS-varningar",
        "summary": "En anställd kom upprepade gånger för sent trots skriftliga erinringar (varningar) och samtal om anställningens upphörande.",
        "legal_provisions_referenced": ["LAS 7 §"],
        "parties": "Unionen mot IT-företag",
        "domskal": "När en arbetstagare systematiskt missköter arbetstiderna trots tydliga varningar om att anställningen är i fara, och ingen förbättring sker, föreligger sakliga skäl.",
        "slut": "Uppsägningen förklaras sakligt grundad."
    },
    {
        "id": "AD_2017_nr_60",
        "case_number": "AD 2017 nr 60",
        "year": 2017,
        "title": "Kringgående av företrädesrätt till återanställning (LAS 25 §) via bemanningsföretag",
        "summary": "En tidigare uppsagd arbetstagare med företrädesrätt förbigicks när arbetsgivaren anlitade bemanningsföretag för samma permanenta arbetsuppgifter.",
        "legal_provisions_referenced": ["LAS 25 §", "LAS 38 §"],
        "parties": "Hotell- och Restaurangfacket mot Restaurangbolag",
        "domskal": "Att kringgå företrädesrätten genom att systematiskt hyra in bemanningspersonal för ett varaktigt behov på samma driftsenhet utgör ett skadeståndsgrundande brott mot LAS 25 §.",
        "slut": "Arbetsgivaren dömdes att betala allmänt skadestånd om 80 000 kr."
    },
    {
        "id": "AD_2017_nr_64",
        "case_number": "AD 2017 nr 64",
        "year": 2017,
        "title": "Åldersdiskriminering vid rekrytering och anställningsintervju",
        "summary": "En meriterad 62-årig sökande valdes bort till förmån för en yngre person med sämre meriter efter kommentarer om 'teamets åldersstruktur'.",
        "legal_provisions_referenced": ["Diskrimineringslagen 1 kap 4 §", "Diskrimineringslagen 2 kap 1 §"],
        "parties": "DO mot Kommunförbund",
        "domskal": "När ålder har haft betydelse för beslutet och arbetsgivaren inte kan visa att det förelegat ett verkligt och avgörande yrkeskrav föreligger otillåten direkt åldersdiskriminering.",
        "slut": "Arbetsgivaren förpliktades betala 100 000 kr i diskrimineringsersättning."
    },
    {
        "id": "AD_2016_nr_22",
        "case_number": "AD 2016 nr 22",
        "year": 2016,
        "title": "Fingerad arbetsbrist (Dold uppsägning av personliga skäl)",
        "summary": "Arbetsgivaren angav arbetsbrist som grund för uppsägning av en fackligt aktiv medarbetare, men AD fann att den verkliga bakgrunden var personliga misshälligheter.",
        "legal_provisions_referenced": ["LAS 7 §"],
        "parties": "Unionen mot IT-bolag",
        "domskal": "Vid påstående om fingerad arbetsbrist har domstolen skyldighet att pröva det verkliga skälet. Om arbetsgivaren döljer personliga skäl bakom en fingerad arbetsbrist måste skälen prövas enligt reglerna för personliga skäl.",
        "slut": "Uppsägningen ogiltigförklarades då sakliga skäl saknades."
    },
    {
        "id": "AD_2016_nr_69",
        "case_number": "AD 2016 nr 69",
        "year": 2016,
        "title": "Omplaceringsskyldighetens omfattning enligt LAS 7 §",
        "summary": "Prövning av hur noggrant och brett en arbetsgivare måste söka lediga tjänster inom hela organisationen innan en uppsägning kan genomföras.",
        "legal_provisions_referenced": ["LAS 7 §"],
        "parties": "Vision mot Region Z",
        "domskal": "Arbetsgivaren måste göra en verklig och noggrann omplaceringsutredning av alla lediga anställningar i företaget som den anställde har tillräckliga kvalifikationer för.",
        "slut": "Uppsägningen ogiltigförklarades på grund av bristfällig omplaceringsutredning."
    },
    {
        "id": "AD_2015_nr_70",
        "case_number": "AD 2015 nr 70",
        "year": 2015,
        "title": "Avbrytande av provanställning (LAS 6 §) och diskriminering p.g.a. graviditet",
        "summary": "En provanställning avbröts bara två dagar efter att arbetstagaren informerat om sin graviditet.",
        "legal_provisions_referenced": ["LAS 6 §", "Diskrimineringslagen 2 kap 1 §", "Föräldraledighetslagen 16 §"],
        "parties": "Diskrimineringsombudsmannen (DO) mot Företag Z",
        "domskal": "En provanställning får visserligen avbrytas utan sakliga skäl enligt LAS 6 §, men ett avbrytande som har orsakssamband med graviditet är direkt diskriminerande och i strid med lag och EU-rätt.",
        "slut": "Företaget dömdes att betala diskrimineringsersättning om 125 000 kr."
    },
    {
        "id": "AD_2015_nr_18",
        "case_number": "AD 2015 nr 18",
        "year": 2015,
        "title": "MBL 11 § – Arbetsgivarens primära förhandlingsskyldighet vid verksamhetsförändring",
        "summary": "Ett företag genomförde en omfattande omorganisation och omfördelning av ansvarsområden utan att först påkalla MBL-förhandling med kollektivavtalsbärande fackförbund.",
        "legal_provisions_referenced": ["MBL 11 §", "MBL 54 §", "MBL 55 §"],
        "parties": "Ledarna mot Tillverkningskoncern",
        "domskal": "Beslut om viktigare förändring av verksamheten eller av arbets- eller anställningsförhållanden får inte fattas eller verkställas innan förhandling enligt MBL 11 § avslutats.",
        "slut": "Arbetsgivaren förpliktades att betala 75 000 kr i allmänt skadestånd till fackförbundet."
    },
    {
        "id": "AD_2014_nr_10",
        "case_number": "AD 2014 nr 10",
        "year": 2014,
        "title": "Skadestånd vid ogiltigförklarad uppsägning (LAS 38 och 39 §)",
        "summary": "Fastställande av allmänt skadestånd för kränkning samt ekonomiskt skadestånd för förlorad inkomst vid felaktig uppsägning.",
        "legal_provisions_referenced": ["LAS 38 §", "LAS 39 §"],
        "parties": "Byggnads mot Byggfirma",
        "domskal": "Allmänt skadestånd enligt LAS syftar till att inskärpa lagens efterlevnad och ge ersättning för den ideella kränkningen. Ekonomiskt skadestånd ersätter faktisk löneminskning.",
        "slut": "Arbetstagaren tilldömdes allmänt skadestånd om 80 000 kr samt full ersättning för förlorad inkomst."
    },
    {
        "id": "AD_2014_nr_15",
        "case_number": "AD 2014 nr 15",
        "year": 2014,
        "title": "Kritikrätt, yttrandefrihet och lojalitetsplikt i privat anställning",
        "summary": "En anställd riktade offentlig kritik mot företagets ledning i media. Arbetsgivaren avskedade den anställde för illojalitet.",
        "legal_provisions_referenced": ["LAS 7 §", "LAS 18 §", "RF 2 kap."],
        "parties": "Unionen mot Privat Vårdbolag",
        "domskal": "I privat anställning gäller en lojalitetsplikt som innebär att kritik i första hand ska framföras internt. Saklig kritik som inte skadar bolaget otillbörligt kan dock inte automatiskt motivera avskedande.",
        "slut": "Avskedandet ogiltigförklarades, men uppsägning ansågs sakligt grundad."
    },
    {
        "id": "AD_2013_nr_78",
        "case_number": "AD 2013 nr 78",
        "year": 2013,
        "title": "Vägran att acceptera skäligt omplaceringserbjudande (LAS 7 §)",
        "summary": "En arbetstagare tackade nej till ett skäligt omplaceringserbjudande med likvärdig lön och befattning.",
        "legal_provisions_referenced": ["LAS 7 §"],
        "parties": "Handels mot Varuhus",
        "domskal": "Om en arbetstagare utan godtagbar anledning avböjer ett skäligt omplaceringserbjudande har arbetsgivaren normalt fullgjort sin omplaceringsskyldighet och kan säga upp medarbetaren.",
        "slut": "Uppsägningen var giltig då arbetsgivaren fullgjort sin omplaceringsskyldighet."
    },
    {
        "id": "AD_2012_nr_52",
        "case_number": "AD 2012 nr 52",
        "year": 2012,
        "title": "Deltidsanställdas företrädesrätt till högre sysselsättningsgrad (LAS 25 a §)",
        "summary": "En deltidsanställd anmälde önskemål om högre sysselsättningsgrad. Arbetsgivaren nyanställde i stället extern personal.",
        "legal_provisions_referenced": ["LAS 25 a §", "LAS 38 §"],
        "parties": "Handels mot Butiksföretag",
        "domskal": "Deltidsanställda som anmält önskemål har företrädesrätt till lediga timmar/tjänster förutsatt tillräckliga kvalifikationer och att arbetsgivarens behov tillgodoses.",
        "slut": "Arbetsgivaren dömdes att betala allmänt och ekonomiskt skadestånd för brott mot LAS 25 a §."
    },
    {
        "id": "AD_2012_nr_82",
        "case_number": "AD 2012 nr 82",
        "year": 2012,
        "title": "Sexuella trakasserier som grund för omedelbart avskedande (LAS 18 §)",
        "summary": "En chef utsatte underordnade anställda för grova sexuella trakasserier och ovälkomna beröringar på arbetsplatsen.",
        "legal_provisions_referenced": ["LAS 18 §", "Diskrimineringslagen 2 kap 1 §"],
        "parties": "Unionen mot Finansbolag",
        "domskal": "Grovt kränkande beteende och sexuella trakasserier, i synnerhet från en överordnad i maktställning, utgör ett fundamentalt brott mot anställningsavtalet och motiverar omedelbart avskedande.",
        "slut": "Avskedandet fastställdes som lagligt. Käromålet ogillades."
    },
    {
        "id": "AD_2011_nr_30",
        "case_number": "AD 2011 nr 30",
        "year": 2011,
        "title": "Avtalsturlistor vid neddragning och god sed på arbetsmarknaden",
        "summary": "Arbetsgivaren och facket träffade en avtalsturlista enligt MBL och kollektivavtal som avvek från lagens turordningsregler (sist in först ut).",
        "legal_provisions_referenced": ["LAS 22 §", "MBL 11 §", "MBL 32 §"],
        "parties": "Enskild medlem mot Arbetsgivarpart och Fackförbund",
        "domskal": "Kollektivavtalsslutande parter har stor frihet att avtala om turordning vid arbetsbrist. En avtalsturlista är giltig så länge den inte strider mot diskrimineringslagstiftning eller god sed på arbetsmarknaden.",
        "slut": "Avtalsturlistan förklarades giltig och band de berörda parterna."
    },
    {
        "id": "AD_2010_nr_83",
        "case_number": "AD 2010 nr 83",
        "year": 2010,
        "title": "Sjukdom, nedsatt arbetsförmåga och arbetsgivarens anpassningsansvar",
        "summary": "Uppsägning av en långtidssjukskriven arbetstagare där arbetsgivaren inte fullt ut undersökt möjligheterna till arbetsanpassning eller omplacering.",
        "legal_provisions_referenced": ["LAS 7 §", "Arbetsmiljölagen 3 kap 2 a §", "SFB 30 kap."],
        "parties": "Kommunal mot Kommun X",
        "domskal": "Sjukdom utgör i sig inte saklig grund för uppsägning. Endast när arbetsförmågan är varaktigt så nedsatt att arbetstagaren inte längre kan utföra arbete av någon betydelse, och alla anpassnings- och rehabiliteringsåtgärder uttömts, kan uppsägning komma i fråga.",
        "slut": "Uppsägningen ogiltigförklarades då arbetsgivaren brustit i rehabiliterings- och anpassningsansvaret."
    },
    {
        "id": "AD_2005_nr_57",
        "case_number": "AD 2005 nr 57",
        "year": 2005,
        "title": "Turordningskretsar och driftsenheter vid geografiskt spridda kontor (LAS 22 §)",
        "summary": "Fastställande av vad som utgör en driftsenhet när ett företag bedriver verksamhet på flera orter och orterna ligger nära varandra.",
        "legal_provisions_referenced": ["LAS 22 §"],
        "parties": "SIF (Unionen) mot Tjänsteföretag",
        "domskal": "Huvudregeln är att varje geografiskt avgränsad arbetsplats utgör en egen driftsenhet. Flera arbetsställen på samma ort slås dock samman till en gemensam turordningskrets.",
        "slut": "Turordningskretsen begränsades till den lokala driftsenheten."
    },
    {
        "id": "AD_2003_nr_24",
        "case_number": "AD 2003 nr 24",
        "year": 2003,
        "title": "Otillåten konkurrerande bisyssla under anställning (Lojalitetsplikt)",
        "summary": "En anställd IT-konsult startade eget bolag inom samma nisch och tog uppdrag från företagets potentiella kunder under pågående anställning.",
        "legal_provisions_referenced": ["LAS 18 §", "Lag om företagshemligheter"],
        "parties": "Teknikarbetsgivarna mot IT-konsult",
        "domskal": "En arbetstagare är under anställningstiden skyldig att iaktta full lojalitet och får inte bedriva konkurrerande verksamhet eller tillskansa sig affärsmöjligheter som tillkommer arbetsgivaren.",
        "slut": "Avskedandet var lagligt och den anställde förpliktades betala skadestånd."
    },
    {
        "id": "AD_1994_nr_101",
        "case_number": "AD 1994 nr 101",
        "year": 1994,
        "title": "29/29-principen och arbetstagarens allmänna arbetsskyldighet",
        "summary": "Klassisk dom som fastslår den s.k. 29/29-principen om ramarna för vad en arbetstagare är skyldig att utföra på arbetsgivarens order.",
        "legal_provisions_referenced": ["MBL 4 §", "Kollektivavtalsrätt"],
        "parties": "Svenska Träindustriarbetareförbundet mot Träindustri",
        "domskal": "Arbetsskyldigheten bestäms av tre kumulativa villkor: 1) Arbetet måste utföras för arbetsgivarens räkning, 2) Arbetet måste ha ett naturligt samband med arbetsgivarens verksamhet och falla inom kollektivavtalets gränser, och 3) Arbetstagaren ska ha allmänna yrkeskvalifikationer för uppgiften.",
        "slut": "Arbetstagaren var skyldig att utföra det anvisade arbetet."
    },
    {
        "id": "AD_2012_nr_69",
        "case_number": "AD 2012 nr 69",
        "year": 2012,
        "title": "Otillåten kvittning mot arbetstagarens slutlön (Kvittningslagen)",
        "summary": "En arbetsgivare gjorde avdrag på en anställds slutlön för påstådd skada på ett tjänstefordon utan skriftligt medgivande eller kvittningsbeslut från Kronofogden.",
        "legal_provisions_referenced": ["Lag (1970:215) om arbetsgivares kvittningsrätt 1–4 §§"],
        "parties": "Transportarbetareförbundet mot Åkeri AB",
        "domskal": "Enligt kvittningslagen får tvångskvittning mot lön endast ske under mycket strikta lagstadgade förutsättningar eller med Kronofogdens tillstånd. Egenmäktigt avdrag på lön är otillåtet och skadeståndsgrundande.",
        "slut": "Arbetsgivaren förpliktades återbetala det innehållna beloppet samt betala 25 000 kr i allmänt skadestånd."
    },
    {
        "id": "AD_2007_nr_107",
        "case_number": "AD 2007 nr 107",
        "year": 2007,
        "title": "Omplaceringsskyldighet och krav på ledig tjänst",
        "summary": "En anställd krävde att arbetsgivaren skulle inrätta en ny tjänst eller dela upp befintliga arbetsuppgifter för att undvika uppsägning.",
        "legal_provisions_referenced": ["LAS 7 §"],
        "parties": "Unionen mot Industriföretag",
        "domskal": "Arbetsgivarens omplaceringsskyldighet är begränsad till befintliga och lediga tjänster. Arbetsgivaren är inte skyldig att inrätta nya tjänster eller omstrukturera organisationen för att skapa en sysselsättning.",
        "slut": "Uppsägningen var sakligt grundad."
    },
    {
        "id": "AD_2024_nr_28",
        "case_number": "AD 2024 nr 28",
        "year": 2024,
        "title": "Hyvling av sysselsättningsgrad under nya LAS (7 b §)",
        "summary": "Prövning av omreglering till lägre sysselsättningsgrad ('hyvling'). Arbetsgivaren tillämpade turordningsreglerna för hyvling enligt 7 b § korrekt genom att erbjuda lägre sysselsättningsgrad först till den med kortast anställningstid.",
        "legal_provisions_referenced": ["LAS 7 b §", "LAS 22 §"],
        "parties": "Handelsanställdas förbund mot Svensk Handel",
        "domskal": "Sedan 2022 års reform i 7 b § LAS måste arbetsgivare vid omreglering till lägre sysselsättningsgrad följa särskild turordning där arbetstagare med kortare anställningstid ska erbjudas sänkt sysselsättningsgrad före de med längre anställningstid inom samma driftsenhet och avtalsområde.",
        "slut": "Arbetsgivarens förfarande fastställdes vara i enlighet med lag."
    },
    {
        "id": "AD_2024_nr_14",
        "case_number": "AD 2024 nr 14",
        "year": 2024,
        "title": "Undantag från turordningen vid arbetsbrist (undantagsregeln om 3 personer)",
        "summary": "En arbetsgivare med 85 anställda undantog 3 nyckelpersoner från turordningen vid en arbetsbristuppsägning enligt de reformerade reglerna i 22 § LAS.",
        "legal_provisions_referenced": ["LAS 22 § sjätte stycket"],
        "parties": "Sveriges Ingenjörer mot Teknikföretagen",
        "domskal": "Enligt nya 22 § sjätte stycket LAS har alla arbetsgivare, oavsett företagets totala antal anställda, rätt att undanta upp till tre arbetstagare som bedöms ha särskild betydelse för den fortsatta verksamheten. Arbetsgivarens skäliga bedömning av särskild betydelse ska respekteras om den inte är uppenbart osaklig eller diskriminerande.",
        "slut": "Uppsägningarna av de övertaliga med längre anställningstid var lagliga."
    },
    {
        "id": "AD_2024_nr_19",
        "case_number": "AD 2024 nr 19",
        "year": 2024,
        "title": "Interimistiskt beslut och anställningens bestånd vid tvist under nya LAS",
        "summary": "En arbetstagare yrkade att anställningen skulle bestå under tvist om uppsägning av personliga skäl. AD tillämpade de nya reglerna i 34 § LAS där anställningen upphör vid uppsägningstidens slut.",
        "legal_provisions_referenced": ["LAS 34 §"],
        "parties": "Arbetstagare mot Tjänsteföretag AB",
        "domskal": "Under nya LAS upphör anställningen vid uppsägningstidens utgång även om tvist om ogiltighet pågår. Interimistiska beslut om att anställningen ska bestå kan endast meddelas i yttersta undantagsfall vid uppenbart lagstridiga uppsägningar.",
        "slut": "Yrkandet om interimistiskt förordnande avslogs."
    },
    {
        "id": "AD_2024_nr_41",
        "case_number": "AD 2024 nr 41",
        "year": 2024,
        "title": "Avbrytande av provanställning och underrättelsefrist (6 § och 31 § LAS)",
        "summary": "En arbetsgivare avbröt en provanställning i förtid utan att lämna underrättelse två veckor i förväg till arbetstagaren och facket.",
        "legal_provisions_referenced": ["LAS 6 §", "LAS 31 §", "LAS 38 §"],
        "parties": "Unionen mot IT-bolag",
        "domskal": "Ett avbrytande av provanställning kräver inte sakliga skäl, men brott mot den två veckor långa underrättelsefristen i 31 § LAS medför skyldighet att betala allmänt skadestånd och lön under varselperioden.",
        "slut": "Provanställningen upphörde men arbetsgivaren dömdes att betala allmänt skadestånd om 20 000 kr."
    },
    {
        "id": "AD_2023_nr_60",
        "case_number": "AD 2023 nr 60",
        "year": 2023,
        "title": "Uppsägning på grund av långvarig sjukdom och uttömt rehabiliteringsansvar",
        "summary": "Arbetsgivaren sades upp efter tre års sjukskrivning då Försäkringskassan bedömt att arbetstagaren saknade arbetsförmåga mot hela den reguljära arbetsmarknaden.",
        "legal_provisions_referenced": ["LAS 7 §", "Arbetsmiljölagen 3 kap. 2 a §", "Socialförsäkringsbalken"],
        "parties": "Kommunal mot Kommun",
        "domskal": "Sjukdom i sig utgör inte sakliga skäl för uppsägning. När arbetsgivaren har fullgjort sitt långtgående rehabiliteringsansvar och anpassningsmöjligheter är uttömda, och arbetstagaren varaktigt inte kan utföra något arbete av betydelse för arbetsgivaren, föreligger dock sakliga skäl.",
        "slut": "Uppsägningen var sakligt grundad."
    },
    {
        "id": "AD_2023_nr_52",
        "case_number": "AD 2023 nr 52",
        "year": 2023,
        "title": "Lojalitetsplikt och sekretess vid övergång till direkt konkurrent",
        "summary": "En nyckelperson på en forskningsavdelning raderade interna filer och vidarebefordrade affärskritisk kod till sin privata e-post inför byte till en konkurrent.",
        "legal_provisions_referenced": ["LAS 18 §", "Lag om företagshemligheter 3-7 §§"],
        "parties": "Teknikföretag mot Civilingenjör",
        "domskal": "Att olovligen föra över arbetsgivarens affärshemligheter och immateriella tillgångar till privat sfär inför byte till konkurrent utgör ett synnerligen grovt avtalsbrott som omedelbart motiverar avskedande och skadestånd.",
        "slut": "Avskedandet fastställdes och arbetstagaren dömdes att betala allmänt och ekonomiskt skadestånd."
    },
    {
        "id": "AD_2023_nr_21",
        "case_number": "AD 2023 nr 21",
        "year": 2023,
        "title": "Diskrimineringsersättning vid graviditet och nekad förlängning av visstidsanställning",
        "summary": "En visstidsanställd kvinna fick besked om att hennes anställning inte skulle förlängas två dagar efter att hon informerat chefen om sin graviditet.",
        "legal_provisions_referenced": ["Diskrimineringslagen 1 kap. 4 §", "Diskrimineringslagen 2 kap. 1 §", "Föräldraledighetslagen 16 §"],
        "parties": "Diskrimineringsombudsmannen (DO) mot Restaurangbolag",
        "domskal": "När ett tidsmässigt nära samband finns mellan graviditetsbesked och nekad förlängning övergår bevisbördan på arbetsgivaren att visa att beslutet inte haft något samband med graviditeten.",
        "slut": "Bolaget dömdes att betala 100 000 kr i diskrimineringsersättning och ekonomiskt skadestånd."
    },
    {
        "id": "AD_2022_nr_48",
        "case_number": "AD 2022 nr 48",
        "year": 2022,
        "title": "MBL-förhandling vid organisationsförändring och outsourcing (11 § MBL)",
        "summary": "Arbetsgivaren fattade beslut om att lägga ut IT-supporten på extern leverantör innan MBL-förhandlingarna enligt 11 § MBL var formellt avslutade.",
        "legal_provisions_referenced": ["MBL 11 §", "MBL 54 §", "MBL 55 §"],
        "parties": "Unionen mot Finansbolag",
        "domskal": "Arbetsgivaren är skyldig att förhandla på eget initiativ innan något bindande beslut fattas eller implementeras. Att föregripa förhandlingen utgör ett allvarligt brott mot MBL.",
        "slut": "Arbetsgivaren förpliktades utge allmänt skadestånd om 100 000 kr till fackförbundet."
    },
    {
        "id": "AD_2022_nr_34",
        "case_number": "AD 2022 nr 34",
        "year": 2022,
        "title": "Krav på sakliga skäl vid samarbetssvårigheter på chefsnivå",
        "summary": "En mellanchef sades upp på grund av samarbetssvårigheter med ledningsgruppen. Arbetsgivaren hade dokumenterat skriftliga samtal och erbjudit coachning samt omplacering.",
        "legal_provisions_referenced": ["LAS 7 §", "LAS 7 a §"],
        "parties": "Ledarna mot Tillverkningsindustri",
        "domskal": "Samarbetssvårigheter måste ha en påtagligt negativ inverkan på verksamheten och arbetsmiljön för att utgöra sakliga skäl. När arbetsgivaren har klargjort problematiken och undersökt omplaceringsmöjligheter är uppsägningen sakligt grundad.",
        "slut": "Uppsägningen var giltig."
    },
    {
        "id": "AD_2021_nr_62",
        "case_number": "AD 2021 nr 62",
        "year": 2021,
        "title": "Kameraövervakning på arbetsplatsen och kränkning av personlig integritet",
        "summary": "En arbetsgivare installerade dolda kameror i personalens fikarum för att utreda misstänkta stölder utan föregående MBL-förhandling eller intresseavvägning.",
        "legal_provisions_referenced": ["MBL 11 §", "GDPR", "Kamerabevakningslagen (2018:1200)"],
        "parties": "Handels mot Detaljhandelsbolag",
        "domskal": "Dold kameraövervakning i personalutrymmen innebär ett mycket allvarligt ingrepp i arbetstagarnas personliga integritet och kräver synnerliga skäl samt MBL-förhandling.",
        "slut": "Arbetsgivaren dömdes till skadestånd gentemot facket och berörda arbetstagare."
    },
    {
        "id": "AD_2021_nr_18",
        "case_number": "AD 2021 nr 18",
        "year": 2021,
        "title": "Avskedande vid stöld av ringa värde (förtroendebrott)",
        "summary": "En butiksanställd med kassaansvar tillgrep varor till ett sammanlagt värde av ca 250 kr från butiken vid upprepade tillfällen.",
        "legal_provisions_referenced": ["LAS 18 §"],
        "parties": "Handels mot Svensk Handel",
        "domskal": "Inom detaljhandel och för anställda i förtroendeställning med kassaansvar innebär tillgrepp av varor, även av ringa värde, ett sådant allvarligt förtroendebrott att avskedande normalt är motiverat.",
        "slut": "Avskedandet var lagligt."
    },
    {
        "id": "AD_2020_nr_68",
        "case_number": "AD 2020 nr 68",
        "year": 2020,
        "title": "Tvåmånadersregeln i 7 § och 18 § LAS vid kännedom om förseelse",
        "summary": "Arbetsgivaren lade en förseelse som inträffat sex månader tidigare till grund för uppsägning, trots att närmaste chef haft kännedom om händelsen redan då.",
        "legal_provisions_referenced": ["LAS 7 § fjärde stycket", "LAS 18 § andra stycket"],
        "parties": "Seko mot Tågoperatör",
        "domskal": "Enligt tvåmånadersregeln får en arbetsgivare inte grunda en uppsägning eller ett avskedande enbart på omständigheter som arbetsgivaren har känt till i mer än två månader före underrättelse eller varsel.",
        "slut": "Uppsägningen ogiltigförklarades på grund av preklusion enligt tvåmånadersregeln."
    },
    {
        "id": "AD_2020_nr_44",
        "case_number": "AD 2020 nr 44",
        "year": 2020,
        "title": "Säkerhetsprövning och saklig grund vid förlorad säkerhetsklassning",
        "summary": "En anställd vid en flygplats nekades förnyat tillträde till säkerhetsklassat område efter registerkontroll hos Säkerhetspolisen.",
        "legal_provisions_referenced": ["LAS 7 §", "Säkerhetsskyddslagen (2018:585)"],
        "parties": "Transport mot Flygplatsbolag",
        "domskal": "När en tjänst enligt lag kräver godkänd säkerhetsprövning och tillträde nekas av behörig myndighet, och omplacering till icke säkerhetsklassad tjänst inte är möjlig, föreligger sakliga skäl för uppsägning.",
        "slut": "Uppsägningen var laglig."
    },
    {
        "id": "AD_2019_nr_51",
        "case_number": "AD 2019 nr 51",
        "year": 2019,
        "title": "Trakasserier på grund av kön och arbetsgivarens utredningsskyldighet",
        "summary": "En kvinnlig anställd anmälde upprepade sexuella trakasserier från en kollega. Arbetsgivaren vidtog inga konkreta utrednings- eller skyddsåtgärder under tre månader.",
        "legal_provisions_referenced": ["Diskrimineringslagen 2 kap. 3 §", "Diskrimineringslagen 5 kap. 1 §"],
        "parties": "DO mot Hotell- och Restaurangföretag",
        "domskal": "Arbetsgivaren har en strikt lagstadgad skyldighet att omedelbart utreda och vidta skäliga åtgärder för att förhindra fortsatta trakasserier så fort kännedom erhållits.",
        "slut": "Arbetsgivaren dömdes att betala 80 000 kr i diskrimineringsersättning."
    },
    {
        "id": "AD_2019_nr_32",
        "case_number": "AD 2019 nr 32",
        "year": 2019,
        "title": "Krav på tillräckliga kvalifikationer vid omplacering och turordning",
        "summary": "Vid arbetsbrist krävde en uppsagd montör att få omplaceras till en ledig tjänst som elkonstruktör med hänvisning till längre anställningstid.",
        "legal_provisions_referenced": ["LAS 22 §", "LAS 7 §"],
        "parties": "IF Metall mot Maskin AB",
        "domskal": "Med 'tillräckliga kvalifikationer' avses att arbetstagaren uppfyller de grundläggande krav som normalt ställs på en nyanställd efter en rimlig upplärningstid (normalt upp till ca sex månader beroende på tjänstens art). Den anställde saknade erforderlig elbehörighet och kravet uppfylldes därför inte.",
        "slut": "Arbetsgivaren hade rätt att inte omplacera till elkonstruktörstjänsten."
    },
    {
        "id": "AD_2018_nr_65",
        "case_number": "AD 2018 nr 65",
        "year": 2018,
        "title": "Skyddsombuds rätt till betald ledighet och agerande vid skyddsstopp",
        "summary": "Ett skyddsombud lade ett skyddsstopp enligt 6 kap. 7 § AML på grund av överhängande rasrisk och nekades lön för tiden av arbetsgivaren.",
        "legal_provisions_referenced": ["Arbetsmiljölagen 6 kap. 7 §", "Förtroendemannalagen 6-7 §§"],
        "parties": "Byggnads mot Byggentreprenör AB",
        "domskal": "Ett skyddsombud som lägger skyddsstopp i god tro skyddas mot löneavdrag och repressalier enligt arbetsmiljölagen och förtroendemannalagen.",
        "slut": "Arbetsgivaren ålades att betala full lön samt allmänt skadestånd för brott mot förtroendemannalagen."
    },
    {
        "id": "AD_2018_nr_37",
        "case_number": "AD 2018 nr 37",
        "year": 2018,
        "title": "Avtalsbrott mot semesterlagens förläggningsregler (11-12 §§ Semesterlagen)",
        "summary": "Arbetsgivaren beordrade ensidigt anställda att ta ut huvudsemester i maj utan samråd och i strid med rätten till fyra sammanhängande veckor under juni–augusti.",
        "legal_provisions_referenced": ["Semesterlagen 11 §", "Semesterlagen 12 §", "Semesterlagen 32 §"],
        "parties": "Hotell- och Restaurangfacket mot Konferensanläggning",
        "domskal": "Arbetstagare har enligt 12 § semesterlagen rätt till en sammanhängande ledighetsperiod om minst fyra veckor under juni–augusti (huvudsemester) om inte kollektivavtal föreskriver annat. Ensidig förläggning i strid med lagen utgör skadeståndsgrundande brott.",
        "slut": "Arbetsgivaren förpliktades betala allmänt skadestånd till de berörda arbetstagarna."
    },
    {
        "id": "AD_2017_nr_58",
        "case_number": "AD 2017 nr 58",
        "year": 2017,
        "title": "Förtroendeskadlig kritik i sociala medier mot arbetsgivaren",
        "summary": "En anställd i en privat vårdinrättning publicerade grova osakliga anklagelser mot ledningen och patienters journaluppgifter på Facebook.",
        "legal_provisions_referenced": ["LAS 18 §", "Lojalitetsplikt"],
        "parties": "Vårdförbundet mot Privat Vård AB",
        "domskal": "I privat anställning begränsas yttrandefriheten av den lojalitetsplikt som följer av anställningsavtalet. Att sprida sekretessbelagda uppgifter och grovt kränkande påståenden offentligt motiverar avskedande.",
        "slut": "Avskedandet var lagligt."
    },
    {
        "id": "AD_2017_nr_24",
        "case_number": "AD 2017 nr 24",
        "year": 2017,
        "title": "Kollektivavtalets företräde vid stridiga anställningsavtalsvillkor",
        "summary": "Ett enskilt anställningsavtal innehöll villkor om lägre övertidsersättning och längre uppsägningstid än vad det tillämpliga kollektivavtalet stadgade.",
        "legal_provisions_referenced": ["MBL 27 §"],
        "parties": "Unionen mot IT-företag",
        "domskal": "Enligt 27 § MBL är villkor i ett enskilt anställningsavtal som strider mot ett kollektivavtal ogiltiga till den del de är till arbetstagarens nackdel.",
        "slut": "Kollektivavtalets förmånligare regler gäller och arbetsgivaren dömdes att utge mellanskillnaden i ersättning."
    },
    {
        "id": "AD_2016_nr_72",
        "case_number": "AD 2016 nr 72",
        "year": 2016,
        "title": "Turordningslista vid flera driftsenheter på samma ort (22 § LAS)",
        "summary": "Ett företag med två fabriker på samma ort upprättade separata turordningslistor utan lokal överenskommelse med facket.",
        "legal_provisions_referenced": ["LAS 22 § tredje stycket"],
        "parties": "IF Metall mot Industrikoncern",
        "domskal": "Flera driftsenheter på samma ort ska sammanslås till en gemensam turordningskrets om den fackliga organisationen begär det vid förhandling enligt 22 § tredje stycket LAS.",
        "slut": "Uppsägningarna bröt mot turordningsreglerna och skadestånd utdömdes."
    },
    {
        "id": "AD_2016_nr_33",
        "case_number": "AD 2016 nr 33",
        "year": 2016,
        "title": "Avskedande vid berusning på arbetsplats med höga säkerhetskrav",
        "summary": "En kranförare på en byggarbetsplats testade positivt för alkohol (0,6 promille) under pågående skift.",
        "legal_provisions_referenced": ["LAS 18 §", "Arbetsmiljölagen 3 kap."],
        "parties": "Byggnads mot Byggbolag",
        "domskal": "Vid säkerhetskänsliga arbetsuppgifter där onykterhet medför direkt fara för kollegors liv och hälsa utgör berusning ett sådant allvarligt avtalsbrott att avskedande är befogat även utan föregående varning.",
        "slut": "Avskedandet var lagligt."
    },
    {
        "id": "AD_2015_nr_46",
        "case_number": "AD 2015 nr 46",
        "year": 2015,
        "title": "Företagsbot och sanktionsavgifter vid brott mot arbetstidslagen (Övertid)",
        "summary": "Ett transportföretag lät förare systematiskt arbeta mer än 200 timmar övertid per år och överträda dygnsvilan om 11 timmar.",
        "legal_provisions_referenced": ["Arbetstidslagen 8 §", "Arbetstidslagen 13 §", "Arbetstidslagen 26 §"],
        "parties": "Arbetsmiljöverket mot Åkeri AB",
        "domskal": "Överträdelser av de tvingande skyddsreglerna i arbetstidslagen avseende maximal övertid och dygnsvila medför sanktionsavgifter och straffansvar.",
        "slut": "Sanktionsavgift fastställdes."
    },
    {
        "id": "AD_2014_nr_88",
        "case_number": "AD 2014 nr 88",
        "year": 2014,
        "title": "Företrädesrätt till återanställning (25 § och 27 § LAS)",
        "summary": "En tidigare uppsagd arbetstagare med företrädesrätt förbigicks när arbetsgivaren anställde en extern konsult på en likvärdig tjänst inom 9 månader.",
        "legal_provisions_referenced": ["LAS 25 §", "LAS 27 §", "LAS 38 §"],
        "parties": "Unionen mot Konsultbolag",
        "domskal": "Arbetsgivaren får inte kringgå företrädesrätten till återanställning genom att ta in inhyrd personal eller dölja en ordinarie anställning som uppdrag när behovet är permanent.",
        "slut": "Arbetsgivaren dömdes att betala allmänt och ekonomiskt skadestånd om 120 000 kr."
    },
    {
        "id": "AD_2013_nr_77",
        "case_number": "AD 2013 nr 77",
        "year": 2013,
        "title": "Uppsägning på grund av arbetsbrist och fingerad arbetsbrist",
        "summary": "En arbetsgivare hävdade arbetsbrist men utredningen visade att den egentliga orsaken var missnöje med arbetstagarens person och fackliga engagemang.",
        "legal_provisions_referenced": ["LAS 7 §", "Förtroendemannalagen 3 §"],
        "parties": "Handels mot Handelsbolag",
        "domskal": "När en arbetsgivare åberopar arbetsbrist men det visas att grunden i själva verket är personliga skäl (fingerad arbetsbrist) ska uppsägningen prövas enligt de strängare kraven för sakliga skäl och omplaceringsutredning.",
        "slut": "Uppsägningen ogiltigförklarades och skadestånd utdömdes."
    },
    {
        "id": "AD_2011_nr_54",
        "case_number": "AD 2011 nr 54",
        "year": 2011,
        "title": "Återkallelse av beviljad semester och skadeståndsansvar",
        "summary": "En arbetsgivare återkallade en anställds redan beviljade sommarsemester en vecka före start utan att synnerliga verksamhetsskäl förelåg.",
        "legal_provisions_referenced": ["Semesterlagen 11 §", "Semesterlagen 32 §"],
        "parties": "Vårdförbundet mot Vårdbolag",
        "domskal": "Ett beslut om semesterförläggning är bindande. Att återkalla beviljad semester kräver oförutsedda och extraordinära händelser som gör arbetstagarens närvaro oundgänglig. I annat fall uppstår skadeståndsansvar för såväl verifierade kostnader (avbokade resor) som allmänt skadestånd.",
        "slut": "Arbetsgivaren förpliktades ersätta reseavbokningskostnader samt betala 20 000 kr i allmänt skadestånd."
    },
    {
        "id": "AD_2010_nr_82",
        "case_number": "AD 2010 nr 82",
        "year": 2010,
        "title": "Löneavdrag och kvittning vid felaktigt utbetald lön (Condictio indebiti)",
        "summary": "Arbetsgivaren gjorde automatiskt löneavdrag månaden efter en felaktig dubbelutbetalning av lön som arbetstagaren redan förbrukat i god tro.",
        "legal_provisions_referenced": ["Kvittningslagen 1-3 §§", "Principen om condictio indebiti"],
        "parties": "Kommunal mot Vårdgivare",
        "domskal": "Huvudregeln vid condictio indebiti är att felaktiga utbetalningar ska återgå, men om mottagaren har mottagit beloppet i god tro och inrättat sig efter det får kvittning inte ske utan arbetstagarens medgivande eller prövning.",
        "slut": "Arbetsgivaren ålades att återbetala det avdragna beloppet."
    },
    {
        "id": "AD_2009_nr_63",
        "case_number": "AD 2009 nr 63",
        "year": 2009,
        "title": "Kollektivavtalsbrott vid utebliven tjänstepensionsinbetalning",
        "summary": "En arbetsgivare bunden av kollektivavtal underlät att teckna och betala avtalsförsäkringar och ITP-tjänstepension för sina tjänstemän under två års tid.",
        "legal_provisions_referenced": ["MBL 26 §", "MBL 54 §", "Kollektivavtalets ITP-plan"],
        "parties": "Unionen mot Konsultbolag",
        "domskal": "Underlåtenhet att betala avtalade pensionspremier och försäkringsavgifter utgör ett allvarligt kollektivavtalsbrott som ger facket rätt till allmänt skadestånd jämte retroaktiv inbetalning av premierna.",
        "slut": "Bolaget dömdes att retroaktivt inbetala pensionspremier samt betala 75 000 kr i allmänt skadestånd till facket."
    },
    {
        "id": "AD_2006_nr_96",
        "case_number": "AD 2006 nr 96",
        "year": 2006,
        "title": "Arbetsgivarintyg och skadestånd vid försenat utfärdande (47 § ALF)",
        "summary": "En arbetsgivare dröjde fem månader med att utfärda ett korrekt ifyllt arbetsgivarintyg efter avslutad anställning, vilket blockerade arbetstagarens a-kasseersättning.",
        "legal_provisions_referenced": ["Lag (1997:238) om arbetslöshetsförsäkring 47 §", "Skadeståndslagen"],
        "parties": "Arbetstagare mot Tidigare Arbetsgivare",
        "domskal": "En arbetsgivare är enligt 47 § lagen om arbetslöshetsförsäkring skyldig att på begäran skyndsamt utfärda arbetsgivarintyg. Uppsåtligt eller vårdslöst dröjsmål som orsakar ekonomisk skada för arbetstagaren ger rätt till skadestånd.",
        "slut": "Arbetsgivaren förpliktades ersätta den ekonomiska förlusten samt betala rättegångskostnader."
    },
    {
        "id": "AD_2003_nr_74",
        "case_number": "AD 2003 nr 74",
        "year": 2003,
        "title": "Varselskyldighet till facket vid uppsägning av personliga skäl (30 § LAS)",
        "summary": "En arbetsgivare underrättade arbetstagaren om uppsägning av personliga skäl men underlät att varsla den lokala arbetstagarorganisationen enligt 30 § LAS.",
        "legal_provisions_referenced": ["LAS 30 §", "LAS 38 §"],
        "parties": "Seko mot Arbetsgivare",
        "domskal": "Arbetsgivaren är skyldig att samtidigt som underrättelse ges till arbetstagaren varsla dennes fackförening. Brott mot 30 § LAS gör inte själva uppsägningen ogiltig men medför alltid skadeståndsskyldighet gentemot facket.",
        "slut": "Arbetsgivaren dömdes att betala allmänt skadestånd till facket."
    },
    {
        "id": "AD_1996_nr_144",
        "case_number": "AD 1996 nr 144",
        "year": 1996,
        "title": "Arbetsgivarens ensidiga rätt att leda och fördela arbetet (§ 32-befogenheten)",
        "summary": "Prövning av gränserna för arbetsgivarens rätt att omorganisera avdelningar och ändra arbetstider inom ramen för gällande kollektivavtal.",
        "legal_provisions_referenced": ["MBL 4 §", "Arbetsledningsrätten"],
        "parties": "Metall mot Verkstadsföretag",
        "domskal": "Arbetsgivaren har enligt svensk rätt en fri arbetsledningsrätt att organisera verksamheten, under förutsättning att lag, kollektivavtal och MBL-förhandlingsplikt respekteras samt att besluten inte är chikanösa eller godtyckliga.",
        "slut": "Arbetsgivarens omorganisation fastställdes vara tillåten inom ramen för arbetsledningsrätten."
    }
]

