import os, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.db.firebase_client import db_client
from src.embeddings.embedder import Embedder

CURATED_COLLECTIVE_AGREEMENTS = [
    {"id": "teknikavtalet_uppsagning", "agreement_name": "Teknikavtalet", "sector": "Industri (Unionen / IF Metall)", "statute": "LAS", "section": "11", "topic": "Uppsägningstid vid arbetsbrist", "rule_content": "För tjänstemän över 55 år med minst 10 års anställningstid gäller 12 månaders uppsägningstid från arbetsgivarens sida vid arbetsbrist.", "statutory_deviation_ref": "Förmånligare än lagens 6 månader (LAS 11 §)."},
    {"id": "teknikavtalet_turordning", "agreement_name": "Teknikavtalet", "sector": "Industri", "statute": "LAS", "section": "22", "topic": "Avtalsturlista vid arbetsbrist", "rule_content": "Parterna kan genom lokal överenskommelse träffa avtal om turordning (avtalsturlista) för att tillgodose företagets kompetensbehov.", "statutory_deviation_ref": "Tillåten avvikelse från LAS 22 § enligt semidispositiva regeln i LAS 2 §."},
    {"id": "almega_it_uppsagning", "agreement_name": "Almega IT & Telekomföretagen", "sector": "IT & Tjänster (Unionen / Sveriges Ingenjörer)", "statute": "LAS", "section": "11", "topic": "Uppsägningstid och omställningsstöd", "rule_content": "1-6 månaders uppsägningstid samt förlängd till 12 månader vid 55 år och 10 års anställning.", "statutory_deviation_ref": "Kompletterar LAS 11 § med omställningsavtal."},
    {"id": "almega_it_overtid", "agreement_name": "Almega IT & Telekomföretagen", "sector": "IT & Tjänster", "statute": "Arbetstidslagen", "section": "7", "topic": "Övertidsinlösen", "rule_content": "Övertidsersättning kan avtalas bort mot högre lön och/eller extra semesterdagar för självständiga roller.", "statutory_deviation_ref": "Ersätter Arbetstidslagens övertidsregler."},
    {"id": "detaljhandel_provanstallning", "agreement_name": "Detaljhandelsavtalet", "sector": "Handel (Svensk Handel / Handels)", "statute": "LAS", "section": "6", "topic": "Provanställning", "rule_content": "Provanställning max 6 månader. Vid avbrytande i förtid ska besked lämnas senast 14 dagar i förväg.", "statutory_deviation_ref": "Specificerar facklig underrättelseskyldighet."},
    {"id": "detaljhandel_ob", "agreement_name": "Detaljhandelsavtalet", "sector": "Handel", "statute": "Arbetstidslagen", "section": "7", "topic": "OB-ersättning", "rule_content": "Kvällar efter 18.15 ger 50% OB. Lördagar efter 12.00 och söndagar ger 100% OB-tillägg.", "statutory_deviation_ref": "Kollektivavtalad ersättning."},
    {"id": "skr_ab_uppsagning", "agreement_name": "SKR Allmänna Bestämmelser (AB)", "sector": "Kommun & Region (SKR / Kommunal / Vision)", "statute": "LAS", "section": "11", "topic": "Uppsägningstid i kommun och region", "rule_content": "För arbetstagare med minst 1 års anställning är uppsägningstiden från arbetsgivaren minst 3 månader.", "statutory_deviation_ref": "Förmånligare startnivå än LAS 11 §."},
    {"id": "skr_ab_semester", "agreement_name": "SKR Allmänna Bestämmelser (AB)", "sector": "Kommun & Region", "statute": "Semesterlagen", "section": "4", "topic": "Semesterdagar per ålder", "rule_content": "25 dagar upp till 29 år, 31 dagar från 30 år, och 32 dagar från 40 års ålder.", "statutory_deviation_ref": "Förmånligare än lagens 25 dagar."},
    {"id": "byggavtalet_varsel", "agreement_name": "Byggavtalet", "sector": "Bygg (Byggföretagen / Byggnads)", "statute": "LAS", "section": "11", "topic": "Varsel och tidsfrister", "rule_content": "Särskilda branschvarseltider gäller gentemot lokal facklig organisation innan uppsägning sker.", "statutory_deviation_ref": "Kompletterar LAS och MBL."},
    {"id": "bemanningsavtalet_garanti", "agreement_name": "Bemanningsavtalet", "sector": "Bemanning (Kompetensföretagen / Unionen / LO)", "statute": "LAS", "section": "4", "topic": "Garantilön mellan uppdrag", "rule_content": "Tillsvidareanställda konsulter har rätt till garantilön (lägst 90% av snittförtjänst) mellan kunduppdrag.", "statutory_deviation_ref": "Branschunik trygghetsregel."},
    {"id": "transport_arbetstid", "agreement_name": "Transportavtalet", "sector": "Transport (Transportföretagen / Transport)", "statute": "Arbetstidslagen", "section": "5", "topic": "Arbetstid för chaufförer", "rule_content": "Beräkningsperioder för ordinarie arbetstid upp till 26 veckor anpassat efter logistikbehov.", "statutory_deviation_ref": "Avviker från Arbetstidslagens 4-veckorsperiod."},
    {"id": "hrf_enstaka_dagar", "agreement_name": "Hotell- och Restaurangavtalet", "sector": "Hotell & Restaurang (Visita / HRF)", "statute": "LAS", "section": "5", "topic": "Anställning för enstaka dagar", "rule_content": "Avtal om arbete för enstaka dagar får träffas vid tillfälliga arbetsanhopningar.", "statutory_deviation_ref": "Branschanpassad anställningsform."},
    {"id": "statligt_villkor_semester", "agreement_name": "Statliga Villkorsavtal-T", "sector": "Statlig sektor (Arbetsgivarverket / Saco-S)", "statute": "Semesterlagen", "section": "4", "topic": "Statlig semesterrätt upp till 35 dagar", "rule_content": "28 dagar t.o.m. 29 år, 31 dagar fr.o.m. 30 år, och 35 semesterdagar fr.o.m. 40 års ålder.", "statutory_deviation_ref": "Upp till 10 dagar fler än Semesterlagens 25 dagar."},
    {"id": "finansavtalet_arbetstid", "agreement_name": "Finans- och Bankavtalet", "sector": "Finans (BAO / Finansförbundet)", "statute": "Arbetstidslagen", "section": "5", "topic": "Kortare veckoarbetstid (38,5 tim)", "rule_content": "Ordinarie arbetstid för heltidsanställd är 38 timmar och 30 minuter per helgfri vecka.", "statutory_deviation_ref": "Kortare än lagens 40 timmar."},
    {"id": "vard_omsorg_dygnsvila", "agreement_name": "Vård- och Omsorgsavtalet", "sector": "Vård (Vårdföretagen / Kommunal)", "statute": "Arbetstidslagen", "section": "13", "topic": "11 timmars dygnsvila och jour", "rule_content": "11 timmars sammanhängande dygnsvila per 24-timmarsperiod som huvudregel.", "statutory_deviation_ref": "Anpassning till EU-arbetstidsdirektivet."},
    {"id": "partihandel_schema", "agreement_name": "Partihandelsavtalet", "sector": "Lager & E-handel (Svensk Handel / Handels)", "statute": "Arbetstidslagen", "section": "12", "topic": "14-dagarsregeln för schema", "rule_content": "Schema ska anslås minst 14 dagar i förväg, annars utgår schemaändringstillägg med 50-100%.", "statutory_deviation_ref": "Stärkt varseltid för schema."},
    {"id": "fastighet_beredskap", "agreement_name": "Fastighetsavtalet", "sector": "Fastighet (Fastigo / Fastighets)", "statute": "Arbetstidslagen", "section": "7", "topic": "Beredskapstjänst och larm", "rule_content": "Fast beredskapsersättning per timme samt övertid (minst 2 tim) vid larmutryckning.", "statutory_deviation_ref": "Ersätter allmänna larmregler."}
]

print(f"Laddar upp {len(CURATED_COLLECTIVE_AGREEMENTS)} kollektivavtal till Firebase...")
for rule in CURATED_COLLECTIVE_AGREEMENTS:
    rule_dict = dict(rule)
    rule_dict["embedding"] = Embedder.get_embedding(rule_dict["topic"] + " " + rule_dict["rule_content"])
    db_client.save_cba_rule(rule_dict)
    print(f" - Sparad i Firestore: {rule_dict['agreement_name']} ({rule_dict['topic']})")

print("\nAlla kollektivavtal är uppladdade till Firebase Firestore!")
